export const SETADMIN = "SETADMIN";
export const SETSELECTEDMENU = "SETSELECTEDMENU";
export const SETACTIVESUBJECT = "SETSUBJECT";
export const SETSITEDETAILS = "SETSITEDETAILS";
export const ADDNAVLINK = "ADDNAVLINK";
